# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Projects
    url: 'projects/'
    weight: 30
  - name: Publications
    url: '/publication/'
    weight: 60
  - name: San Martin 
    url: '/san_martin/'
    weight: 50
  - name: People 
    url: '#miembros'
    weight: 20
    weight: 40    
  - name: Post
    url: '#posts'
    weight: 80   
  - name: Gallery
    url: '/gallery'
    weight: 80    
  - name: Contact
    url: '#contact'
    weight: 130
    
